name: madi.baseline.eihcl.research
channels:
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit
  - absl-py
  - pyparsing
  - pip
  - pip:
    - numpy
    - torch
    - torchvision
    - gym
    - importlib-metadata
    - pillow
    - termcolor
    - imageio
    - imageio-ffmpeg
    - opencv-python
    - xmltodict
    - tqdm
    - einops
    - kornia
    - wandb
    - captum
    - pandas
